name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          NODE_OPTIONS=--openssl-legacy-provider npm install

      - name: Build app
        run: npm run electron:build

      - name: Upload release asset
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: dist_electron/
