name: Build Pack
on:
  push:
    branches:
      - main # master 分支 push 时触发工作流
jobs:
  pack: # 打包任务
    runs-on: windows-latest # 在 windows 系统中运行
    steps:
      - uses: actions/checkout@v2 # 下载仓库代码到工作流机器中
      - name: Set up GitHub Token
        run: echo "${{ secrets.GH_TOKEN }}" >> $GH_TOKEN
      - name: Install and Pack # 安装依赖并且进行构建
        run: |
          set NODE_OPTIONS=--openssl-legacy-provider
          npm install
          npm run electron:build
        env:
          NODE_OPTIONS: --openssl-legacy-provider # 在这里设置环境变量
      - name: Upload file # 将构建产物进行上传
        uses: actions/upload-artifact@v2
        with:
          name: packs # 上传后的名字
          path: packs # 将 packs 目录进行上传
