name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Build app
        run: npm run electron:build

      - name: Upload release asset
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: dist_electron/
